// require("dotenv").config({ path: "./.env" });
import "dotenv/config";
export const SECRET = process.env.APP_SECRET;
export const APP_DB = process.env.APP_DB;
export const PORT = process.env.PORT;
export const BCRYPT_SALT_ROUNDS = process.env.BCRYPT_SALT_ROUNDS;
export const APP_EXPRESS_SESSION_SECRET = process.env.APP_EXPRESS_SESSION_SECRET;
export const APP_JWT_ENCRYPTION_SECRET = process.env.APP_JWT_ENCRYPTION_SECRET;
export const APP_JWT_ACCESSTOKEN_EXPIRY = process.env.APP_JWT_ACCESSTOKEN_EXPIRY;
export const APP_JWT_ACCESSTOKEN_EXPIRY_MILLIS = process.env.APP_JWT_ACCESSTOKEN_EXPIRY_MILLIS;
export const APP_JWT_REFRESHTOKEN_EXPIRY = process.env.APP_JWT_REFRESHTOKEN_EXPIRY;
export const APP_JWT_REFRESHTOKEN_EXPIRY_MILLIS = process.env.APP_JWT_REFRESHTOKEN_EXPIRY_MILLIS;
export const EMAIL = process.env.EMAIL;
export const PASS = process.env.PASS;
export const APP_URL = process.env.APP_URL;
export const APP_VERIFICATIONTOKEN_EXPIRY = process.env.APP_VERIFICATIONTOKEN_EXPIRY;
